dataset:
  value: CUB
dataroot:
  value: ./data/xlsa17/data
image_embedding:
  value: feature_CUB_VIT_769
  # value: res101
class_embedding:
  value: sent
syn_num:
  value: 500
gzsl:
  value: True
preprocessing:
  value: True
standardization:
  value: False
workers:
  value: 128
batch_size:
  value: 128
resSize:
  value: 768
attSize:
  value: 1024
nz:
  value: 1024
ngh:
  value: 4096
ndh:
  value: 4096
nepoch:
  value: 500
cls_nepoch:
  value: 2000
critic_iter:
  value: 5
lambda1:
  value: 10
lambda2:
  value: 10
lr:
  value: 0.0001
feed_lr:
  value: 0.00001
dec_lr:
  value: 0.0001
classifier_lr:
  value: 0.001
beta1:
  value: 0.5
cuda:
  value: True
encoded_noise:
  value: True
manualSeed:
    # value: 8488
    value: 3483
nclass_all:
  value: 200
validation:
  value: False
encoder_layer_sizes:
  value: [8192, 4096]
decoder_layer_sizes:
  value: [4096, 8192]
gammaD:
  value: 10
gammaG:
  value: 10
gammaG_D2:
  value: 1000
gammaD2:
  value: 1000
latent_size:
  value: 1024
conditional:
  value: True
a1:
  value: 10.
a2:
  value: 10.
recons_weight:
  value: 0.1
feedback_loop:
  value: 2
freeze_dec:
  value: False
result_root:
  value: ./result_new
center_margin:
  value: 200
center_weight:
  value: 0.5
incenter_weight:
  value: 0.8
cls_weight:
  value: 0.2
nclass_seen:
  value: 150
latensize:
  value: 1024
i_c:
  value: 0.1
lr_dec:
  value: False
lr_dec_ep:
  value: 1
final_classifier:
  value: softmax
k_nn:
  value: 5
feature_component:
  value: FR_h_a
pre_seed:
  value: 214
pre_dim_v:
  value: 300
pre_bs:
  value: 50
pre_iters:
  value: 1101
pre_normalize_V:
  value: False
pre_normalize_F:
  value: True
